#! /bin/sh
# ==========================================================
# ███████╗██████╗ 
# ██╔════╝██╔══██╗  Edwin Páez (M8-Babbage)
# █████╗  ██║  ██║  https://github.com/M8-Babbage
# ██╔══╝  ██║  ██║
# ███████╗██████╔╝
# ╚══════╝╚═════╝ 
#
# A customized bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm
# ==========================================================

# Configurar dispositivos de salida por medio de un script generado usando arandr
# Si la entrada HDMI-1 está conectada configuramos los monitores con sus posiciones, basados en arandr
if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
  xrandr --output eDP-1 --primary --mode 1366x768 --pos 225x1080 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-2 --off
  bspc monitor eDP-1 -d I II III IV &
  bspc monitor HDMI-1 -d V VI VII VIII &
else
  xrandr --output eDP-1 --primary --mode 1366x768 --pos 225x1080 --rotate normal --output HDMI-1 --off --output DP-1 --off --output HDMI-2 --off
  bspc monitor eDP-1 -d I II III IV &
fi

# Iniciamos los servicios
pkill sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
pkill nitrogen
nitrogen --restore &
pkill dunst
dunst -conf ~/.config/dunst/dunstrc &
pkill volumeicon
volumeicon &
pkill cbatticon
cbatticon &
pkill udiskie
udiskie -t &
pkill nm-applet
nm-applet &
pkill flameshot
flameshot &
exec ~/.config/polybar/launch.sh

#### BSPWM configuration ####
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color       "#4c566a"
bspc config active_border_color	      "#1e1e1e"
bspc config focused_border_color	    "#5e81ac"
bspc config presel_feedback_color	    "#5e81ac"
bspc config urgent_border_color 	    "#dd2727"