#! /bin/sh
# ███████╗██████╗ 
# ██╔════╝██╔══██╗  Edwin Páez (M8-Babbage)
# █████╗  ██║  ██║  https://github.com/M8-Babbage
# ██╔══╝  ██║  ██║
# ███████╗██████╔╝
# ╚══════╝╚═════╝ 
#
# A customized bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &

bspc monitor Virtual-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
