#! /bin/sh
# ███████╗██████╗ 
# ██╔════╝██╔══██╗  Edwin Páez (M8-Babbage)
# █████╗  ██║  ██║  https://github.com/M8-Babbage
# ██╔══╝  ██║  ██║
# ███████╗██████╔╝
# ╚══════╝╚═════╝ 
#
# A customized bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

pkill sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
pkill polybar
polybar &
pkill nitrogen
nitrogen --restore &
pkill flameshot
flameshot &
pkill volumeicon
volumeicon &
pkill cbatticon
cbatticon &
pkill udiskie
udiskie -t &
pkill np-applet
nm-applet &
pkill dunst
dunst -conf ~/.config/dunst/dunstrc &
pkill picom
picom -f --daemon --config ~/.config/picom/picom.conf &

bspc monitor Virtual-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

#### BSPWM configuration ####
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color       "#4c566a"
bspc config active_border_color	      "#1e1e1e"
bspc config focused_border_color	    "#5e81ac"
bspc config presel_feedback_color	    "#5e81ac"
bspc config urgent_border_color 	    "#dd2727"
